spring.application.name=viatab-backend
server.port=8080

spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/viatab_db}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:viatab_user}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:admin}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.jdbc.time_zone=UTC

viatab.jwt.secret=viatabSuperSecretKeyForJwtTokenGeneration
viatab.jwt.expiration-ms=86400000